server:
  port: 8763
  forward-headers-strategy: framework

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:eureka:8763/eureka}
    registerWithEureka: false
    fetchRegistry: false